spring.datasource.url=jdbc:mysql://localhost:3306/novabank

spring.datasource.username=root

spring.datasource.password=Anita

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true



server.port=8080
 spring.application.name=backend

# JWT Secret (development only)
jwt.secret=ReplaceThisWithAReallyLongRandomSecretKeyForDevelopment123456789

# Token Expiry (24 hours)
jwt.expiration=86400000